Class Aidoc.POC.Production.Messages.Hello Extends (%Persistent, Ens.Request)
{

Storage Default
{
<Data name="HelloDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^Aidoc.REQ.HelloD</DataLocation>
<DefaultData>HelloDefaultData</DefaultData>
<IdLocation>^Aidoc.REQ.HelloD</IdLocation>
<IndexLocation>^Aidoc.REQ.HelloI</IndexLocation>
<StreamLocation>^Aidoc.REQ.HelloS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
